feat: hello terraform provider
PrefectHQ/terraform-provider-prefect pull request #1
Opened 2022-07-25 11:01 UTC by tekumara

Hello terraform provider for [Prefect](prefect.io) 👋 

This PR adds the provider with support for project & service account resources in Prefect Cloud version 1.

The next PR will add CI/CD for testing and publishing to the Terraform Registry.

2022-08-29 15:14 UTC, gabcoyne commented on LICENSE
> +   Copyright 2022 Xero
Prefect will be owning the copyright here, can we update this?

2022-08-29 15:20 UTC, gabcoyne requested changes

2022-08-29 15:20 UTC, gabcoyne commented on LICENSE
> +   Copyright 2022 Xero
Lets change this copyright to Prefect

2022-08-31 16:06 UTC, gabcoyne approved these changes

2022-08-31 16:46 UTC, jamiezieziula approved these changes

2022-08-31 18:33 UTC, merged